### ISSUE TITLE
Comparison / interoperability with Flax

### ISSUE THREAD

**Issue by asrvsn** [deepmind/dm-haiku#105]
Hello, I recently came across this library, and I was wondering about how its featureset/design compares with [Flax](https://github.com/google/flax), and whether there are use cases where one is better than the other. In particular, the handling of parameters/state in models & whether Haiku models can be used with Flax optimizers fairly easily (since it looks like some additional architectures are implemented in this library). 

Thanks!

**Comment by tomhennigan** [comment]
Hi @asrvsn, I should caveat by saying I am not very familiar with Flax's implementation (or other JAX NN libraries other than stax), although I know the authors and they're all awesome.

If there are any places where the pure functions returned from `hk.transform` (e.g. the init and apply function) or data structures (e.g. the params/state dict) cause issues with using Flax (or any other JAX library) then we will consider this a bug and work to fix it.

> how its featureset/design compares with Flax

AFAIK Haiku and Flax offer similar functionality when it comes to defining neural networks using modules. The API differs slightly between Flax and Haiku, but overall I would expect you to be able to implement any state of the art machine learning model with either library.

Flax is a bit more batteries included, and comes with optimizers, mixed precision and some training loops (I am told these are decoupled and you can use as much or as little as you want). Haiku aims to just solve NN modules and state management, it leaves other parts of the problem to other libraries (e.g. [`optax`](https://github.com/deepmind/optax) for optimization).

> are use cases where one is better than the other

Haiku is designed to be a port of Sonnet (a TF NN library) to JAX. So Haiku is a better choice if (like DeepMind) you have a significant amount of Sonnet+TF code that you might want to use in JAX and you want migrating that code (in either direction) to be as easy as possible.

I think otherwise it comes down to personal preference. Within Alphabet there are 100s of researchers using each library so I don't think you can go wrong either way. At DeepMind we have standardised on Haiku because it makes sense for us. I would suggest taking a look at the example code provided by both libraries and seeing which matches your preferences for structuring experiments. I think you'll find that moving code from one library to another is not very complicated if you change your mind in the future.

> whether Haiku models can be used with Flax optimizers fairly easily

We've been discussing this a bit recently with Flax team since some other users have asked. AFAIK things work just fine, but you'll need to convert Haiku's parameters to regular dictionaries before calling into Flax. This is because Haiku uses an optimized Mapping type called `FlatMapping` which historically offered a significant performance boost when combined with jit/pmap, but this does not support `treedef.flatten_up_to` which is used in Flax and `jax.sharded_jit`.

We're in the process of fixing this, but for now you'll need to convert the type before calling Flax:

```python
params = .. some haiku params ..
params = hk.data_structures.to_mutable_dict(params)
params = flax_optimizer.step(grads, params)  # pseudocode, i don't know their api
```

I think otherwise things should work.

**Comment by asrvsn** [comment]
Thanks for the detailed reply! 
It sounds like they can be pretty easily composed with one another -- I'll try it out and report back if there are any issues!

**Comment by tomhennigan** [comment]
Sounds good! Just as one piece of advice, I would suggest sticking with the module abstraction from one library or the other. For example if there some Haiku modules you want to use with Flax nn.Modules then I would suggest porting the code from one library to the other. Trying to combine the two will likely cause more friction than value.
