### ISSUE TITLE
Custom query_size in MultiHeadAttention?

### ISSUE THREAD

**Issue by KristianHolsheimer** [deepmind/dm-haiku#116]
I have a question about `MultiHeadAttention`. I'm relatively new to transformers, so apologies if this is a stupid question.

What would be a use-case for have a `query_size != key_size`?

From reading the code, this seems to lead to incompatible shapes, e.g.

```python
import jax
import jax.numpy as jnp
import haiku as hk

rngs = hk.PRNGSequence(42)

# shape: (batch_size, seq_len, vector_dim)
q = jax.random.normal(next(rngs), shape=(2, 3, 5))
k = jax.random.normal(next(rngs), shape=(2, 3, 5))
v = jax.random.normal(next(rngs), shape=(2, 3, 5))

def f(q, k, v):
  mha = hk.MultiHeadAttention(num_heads=7, key_size=11, query_size=13, w_init_scale=1.)
  return mha(q, k, v)

# init
init, apply = hk.transform(f)
params = init(next(rngs), q, k, v)  # raises ValueError
```
> ValueError: Size of label 'd' for operand 1 (13) does not match previous terms (11).

**Comment by tomhennigan** [comment]
Hi @KristianHolsheimer , thanks for the query. I spoke with @inoryy and we couldn't think of a case where this would make sense. Also re-reading the paper it is clear that the authors intended for query and key size to always be the same.

![image](https://user-images.githubusercontent.com/28017/112512815-9eda2880-8d8b-11eb-80d6-696c978b726c.png)

I'll send a PR dropping this ctor argument. Usually we avoid making API breaking changes, but in this case we're comfortable doing so since (1) we could not find any users relying on it (2) setting this to != key_size results in an error (so anyone who is setting this optional parameter can simply delete their use of it).

**Comment by KristianHolsheimer** [comment]
Thanks @tomhennigan !

Yeah, thinking about it more, the shapes of `query` and `key` may be only be differ in their sequence length (named `'t'` and `'T'` here).
