### ISSUE TITLE
Does dm-haiku compatible with python 3.8?

### ISSUE THREAD

**Issue by smao-astro** [deepmind/dm-haiku#184]
Hi,

I am using dm-haiku with python 3.7, everything work well. Now I want to use some feature of other package only available on python 3.8, but I saw
https://github.com/deepmind/dm-haiku/blob/d8762f0d97246f5d1c1992a6dba903226fad327d/requirements.txt#L5
Any chance I can use 3.8? Any suggestions?

Thanks!

**Comment by tomhennigan** [comment]
Hi @smao-astro , Haiku works and [is tested against Python 3.7 and 3.8](https://github.com/deepmind/dm-haiku/runs/3084871916). It is likely to work with more recent versions of Python too.

That line in the requirements file says this dependency is required only if your Python version is less than 3.8. It just avoids installing the dependency because the typing functionality needed is part of the standard library from 3.8.

**Comment by smao-astro** [comment]
Thanks!
