### ISSUE TITLE
Support custom param root in hk.get_parameter()

### ISSUE THREAD

**Issue by jaideepheer** [deepmind/dm-haiku#188]
I am trying to implement a NAS algorithm and in my network I have multiple cells that share some architecture parameters.

Currently, to share a parameter, I have to pass it as argument to the `__init__` function and create it with `hk.get_parameter` somewhere higher up in the tree.

It would be nice if `hk.get_parameter` accepted a `rootPath` parameter so that I can tell it to get a parameter that is global to the tree instead of one that is local to the current module.

**Comment by tomhennigan** [comment]
Hi @jaideepheer , thanks for the details! We'd prefer to not make get_parameter more complex at the moment, it is already a new concept for users and a bit confusing to folks getting started.

I think your proposed work around is good (passing in the parameter to one of the module methods). You may also find it convenient to pass in a module rather than the parameter itself. You may find that some common code can be put into this "shared"/"common" module and reused between both architectures.

For folks reading along I made an example of what I meant here: https://colab.research.google.com/gist/tomhennigan/0dfe032cff5210aa16f9671b07f87bb1/example-of-parameter-sharing-via-shared-module.ipynb
