### ISSUE TITLE
Probabilistic programming interface

### ISSUE THREAD

**Issue by filangel** [deepmind/dm-haiku#22]
Is there a plan of adding probabilistic programming interface, such as [`rlax.distributions`](https://github.com/deepmind/rlax/blob/master/rlax/_src/distributions.py) or [`tfp`](https://github.com/tensorflow/probability).

Right now, [`numpyro`](https://github.com/pyro-ppl/numpyro/) is the only JAX-powered library for this. I could add an example of how to combine `dm-haiku` and `numpyro` if you want.

**Comment by trevorcai** [comment]
To be honest, I haven't yet explored probabilistic programming (past using `tfp.distributions` for other projects in the past) in sufficient depth to give a strong answer here.
I like declaring things out of scope where sensible; if Haiku composes with `numpyro` or other pure-functional libraries, we'll just declare this out of scope!

My limited experience with Haiku + RLAX and Sonnet + TFP has given me no indicator that Haiku won't compose with probabilistic programming libraries; I've previously written VAEs in Haiku with no issues.

That said, I'd love to see an example combining Haiku & `numpyro`, though it could be tricky for us to merge internally.

Any thoughts, @ibab ?

**Comment by ibab** [comment]
I'm not very familiar with `numpyro` unfortunately, but from a quick glance it looks like you should be able to use Haiku networks inside of `numpyro` program. If there are any issues with that or if there are any other libraries that Haiku doesn't compose with we'd be interested to hear about it!
We want Haiku to stay small and focused on neural networks, so we probably won't be adding support for probabilistic programming. Ideally we'd like Haiku to compose well with other libraries so that you're not locked into a single choice.

**Comment by ibab** [comment]
Here's an example of how to replace the stax networks in the numpyro VAE example with Haiku:
https://github.com/ibab/numpyro/commit/bdb1a595d1737715a288eb8498587b676f505c30
We could add a Haiku to stax converter function to Haiku to streamline use cases like this.

**Comment by joaogui1** [comment]
Haiku composes with numpyro, I was porting OpenAI's spinning up with Deep RL and used numpyro instead of pytorch.distributions and it worked out fine

**Comment by trevorcai** [comment]
Thanks for the confirmations, Joao and Igor. Closing for now.
