### ISSUE TITLE
Disable __setattr__ in frozendict

### ISSUE THREAD

**Issue by KristianHolsheimer** [deepmind/dm-haiku#25]
There can be some strange behavior in frozendict due to attr assignment:
```python
import haiku as hk

frozen = hk.data_structures.to_immutable_dict({'a': 'foo'})
print(frozen['a'], frozen.a)  # --> foo foo
frozen.a = 'bar'              # should raise error
print(frozen['a'], frozen.a)  # --> foo bar
```
My suggestion would be to simply disallow any `setattr` on `frozendict`.

Also, as a side note, please expose `frozendict` to the public api. Right now, the only way to access it is through `haiku._src.data_structures.frozendict`.

**Comment by tomhennigan** [comment]
Thanks for the patch @KristianHolsheimer ! It might be worth noting that Haiku doesn't require the use of `frozendict`, if you want to create your own `dict`s by hand (as opposed to using `f.init` etc) you can use `dict` (or any subclass of `Mapping` that you prefer).

We haven't exposed the type since our plan is to shortly deprecate `frozendict` and replace it with `FlatMapping` (almost finished impl in `data_structures.py`) which has a flat internal representation and is a lot faster when used with JAX APIs like `jax.tree_map` or when passed in and out of `jit`/`pmap` (right now passing a `dict` or `frozendict` into these APIs is `O(nlogn)` since it requires sorting the keys to flatten).

If you want to freeze your dicts for some reason (e.g. like us you prefer passing around immutable data structures) then there are public endpoints to do so, they just don't expose the type directly (such that we can swap the impl out for FlatMapping):

```python
d = {}
immutable = hk.data_structures.to_immutable_dict(d)
mutable = hk.data_structures.to_mutable_dict(immutable)
```

**Comment by KristianHolsheimer** [comment]
I see. That's interesting.. I really like the `jax.tree_util` module, but it's easy to forget the overhead of flattening and unflattening pytrees with every operation. I really like the FlatMapping idea, to only do the work when representing the data to the user and keep it flat otherwise (if I'm understanding it correctly).
