### ISSUE TITLE
Why do we input the dummy matrix in apply()?

### ISSUE THREAD

**Issue by EngineerKhan** [deepmind/dm-haiku#253]
I am new to Haiku, and while applying the transforms, I can understand `init()` using the `x` as a dummy for shape; though why do we need it in `apply()` when we are already passing the initialized matrix there having the same size? Is it a redundant feature or does it serve some purpose?

**Comment by tomhennigan** [comment]
Hi @EngineerKhan , the value passed to apply (e.g. [here in our MNIST example](https://github.com/deepmind/dm-haiku/blob/main/examples/mnist.py#L64)) should be a real (non-dummy) input.

Typically you don't pass dummy values to `apply`. For `init` you can pass a dummy value because for most neural networks you can initialise parameters based just on the shape of inputs passing through the network (their value is not necessary).
