### ISSUE TITLE
deepcopy broken for new FlatMapping

### ISSUE THREAD

**Issue by KristianHolsheimer** [deepmind/dm-haiku#31]
Hi there,

I noticed there have been some changes to `FlatMapping`.

I can imagine that you don't really see the need for deepcopying a `FlatMapping` as it's supposed to be immutable. But just so you know, deepcopy doesn't work anymore:
```python
from haiku._src.data_structures import FlatMapping

m = FlatMapping.from_mapping({'foo': 'bar'})
deepcopy(m)  # raises TypeError: can't pickle jaxlib.pytree.PyTreeDef objects
```

P.S. I stumbled upon this because I'm deriving a subclass with limited mutability from FlatMapping (whose leaves are all DeviceArrays). I'm using `deepcopy` for my target-network / behavior-policy weights.

I added a custom implementation to my derived class:
```python
class Foo(FlatMapping):
    ...

    def __deepcopy__(self, memo):
        leaves, treedef = self.flatten()
        return self.__class__((deepcopy(leaves), treedef))
```

Also.. thanks for the speed-up in FlatMapping!

**Comment by tomhennigan** [comment]
Thanks for noticing, this is mostly @LenaMartens hard work!

We're working on a patch to get all our `frozendict` tests passing for `FlatMapping` and this includes covering copy/deepcopy/pickle etc. It's basically there, a missing puzzle piece was deepmind/tree@f18a0f6b25f7edbebca021d447f0323c48a7d633 and I hope once a new `dm-tree` release is pushed (I think we can do this today) it will be good to go 😄 

For pickle support I was planning to go with:

```
  def __reduce__(self):
    return FlatMapping.from_mapping, (self.to_mapping(),)
```

I think this is nice since it is forward and backwards compatible (e.g. a FlatMapping saved by Haiku version N would be loadable by Haiku version N-1 and N+1) assuming the pickled representation of dict does not itself change (e.g. if you keep your Python version the same this will be the case and typically between minor versions the pickle format for builtins does not change).

I'll tag this issue with the changes so you're kept up to date.

**Comment by KristianHolsheimer** [comment]
Awesome, thanks!
