### ISSUE TITLE
Feeding in dictionary of data?

### ISSUE THREAD

**Issue by IanQS** [deepmind/dm-haiku#333]
Hey all! 

One thing I really enjoyed about Tensorflow was the feeddict option where I could then access the data by the keys to easily access and process the data in chunks. E.g

```
{
    "data_to_be_embedded": ... #Some (batch_size, N , M) matrix
    "timeseries data": ... # (batch_size, timeseries_window)
}
```

I suppose one option would be to define multiple models and wrap them all into a single function which applies them `key-value` by `key-value`. Is there a more "idiomatic" way of doing this in Haiku?

**Comment by tomhennigan** [comment]
Hi @IanQS , feeding tensors in a graph by name (which is what feed dict in TF1 enabled) is not something supported by JAX or by Haiku, however you may have some luck with [Oryx, which supports "reap" and "sow" to fetch and feed intermediate values in a JAX program](https://colab.research.google.com/github/tensorflow/probability/blob/master/spinoffs/oryx/examples/notebooks/a_tour_of_oryx.ipynb).

**Comment by IanQS** [comment]
Thanks! Unfortunately, it seems like a rather small library so I'll find workarounds based on Haiku.

Can I ask how you or how the team at DM would handle the data coming in in the format I mentioned above? I'm assuming having some intermediary that accepts a dictionary and spits out a N-d array that can be consumed directly by Haiku?

**Comment by tomhennigan** [comment]
> Thanks! Unfortunately, it seems like a rather small library so I'll find workarounds that let me continue on with Haiku.

The two libraries compose nicely, so it is an option to use both 😄 https://colab.research.google.com/gist/tomhennigan/e999e891bdb0e6da94cf3239a098f8b0/example-of-using-haiku-with-oryx.ipynb

It might be useful context that the author of Oryx is now a member of the core JAX team at Google and it has a decent amount of usage in DeepMind (mostly for extracting intermediate values). Personally I consider it a stable and mature part of the JAX ecosystem.

> Can I ask how you or how the team at DM would handle the data coming in in the format I mentioned above? I'm assuming having some intermediary that accepts a dictionary and spits out a N-d array that can be consumed directly by Haiku?

I suspect most people would just write a function or module accepting a dict and process it as you describe (key-wise) or if they wanted the actual TF "feeding named tensors" experience then I'm fairly confident they would use Oryx (although most of our usage of this library is to fetch values rather than to feed them).

**Comment by IanQS** [comment]
Thank you! Do you know if there are any plans to split oryx out of TFP? It seems generic enough that it could stand on its own. 

I'm not married to the concept of "feeding named tensors". I just enjoyed the introspection afforded in that I can see how the different inputs are flowing through and going to the right places. Also, I just found it more flexible since any given model can choose to consume or drop features on the fly

**Comment by IanQS** [comment]
Thank you! I'm closing hte issue out now
