### ISSUE TITLE
BatchNorm with CNN

### ISSUE THREAD

**Issue by Nanboy-Ronan** [deepmind/dm-haiku#397]
I have encoutered the following issue while applying BN in models (simple CNN for example).
```  File "/usr/local/lib/python3.7/dist-packages/haiku/_src/transform.py", line 115, in init_fn
    raise ValueError("If your transformed function uses `hk.{get,set}_state` "
ValueError: If your transformed function uses `hk.{get,set}_state` then use `hk.transform_with_state`.
```
My simple code snippet is
```
class CNN1(CNN):
    def __call__(self, x):
        batch_size = x.shape[0]

        x = hk.Conv2D(32, kernel_shape=3, stride=1, padding="VALID")(x)
        x = hk.BatchNorm(create_scale=True, create_offset=True, decay_rate=0.999)(x, True)
        x = activation(x)
        x = hk.MaxPool(window_shape=2, strides=2, padding="VALID")(x)

        x = hk.Conv2D(64, kernel_shape=3, stride=1)(x)
        x = hk.BatchNorm(create_scale=True, create_offset=True, decay_rate=0.999)(x, True)
        x = activation(x)
        x = hk.MaxPool(window_shape=2, strides=2, padding="VALID")(x)
```
I have tried calling hk.transform_with_state(CNN1) but it does not help. I wonder if I did anything wrong?

**Comment by tomhennigan** [comment]
Hi @Nanboy-Ronan , Haiku is built around the idea of transforming functions rather than module objects. I've put an example of using the module you defined above in this gist, I hope that is usefu: https://colab.research.google.com/gist/tomhennigan/73835e426fa41f5a95ccc80302997aa3/cnn1-example.ipynb

The key difference is passing a function (that creates/uses modules and returns tensors) to `transform_with_state` rather than a constructor.
