### ISSUE TITLE
How to duplicate a module's parameters similar to semantics of deepcopy a PyTorch module?

### ISSUE THREAD

**Issue by jjyyxx** [deepmind/dm-haiku#520]
In reinforcement learning, target network is a common technique to assist off-policy value learning. In PyTorch-based implementations, `target_q_network = deepcopy(q_network)` could create a target network with initial parameter identical to the value network. But I found it not easy to achieve in haiku. This is different from ways in the parameter sharing document, as the parameters are separately updated after initialization. Several ways I could think of
1. Create two separate modules, then manually edit the parameter dict after init (seems not elegant and error-prone to me. I wish to achieve this inside the init transform)
2. `deepcopy(q_network)` leads to only one set of parameters (as expected in haiku)
3. Somehow use a custom parameter initializer or `custom_creator`? Not sure how to achieve this.

**Comment by tomhennigan** [comment]
Hi @jjyyxx , in JAX all tensors (including parameters) are immutable. This means you don't need to deepcopy to clone their value, you can just make multiple references to them:

```python
def q_network(..):
  # .. use some haiku modules ..

q_network = hk.transform(q_network)

# Create our initial model params.
params = q_network.init(rng, ..)

# Because tensors in JAX are are immutable, we don't need to make a copy
# of the model params for the target network, we can just reference the same
# tensors.
target_params = params

while training:
  # params will be a new set of parameters. This will not update `target_network`.
  params = train_step(params, ..)

  if update_target_params:
    # Again, because tensors are immutable we don't need to make a copy.
    target_params = params
```

**Comment by jjyyxx** [comment]
Thanks for your clarification @tomhennigan

I understand the immutable nature of Jax tensors. But what I would like to achieve is "duplicate nested modules" for a parent module.

```python
class A(hk.Module):
  def __init__():
    self.q = Q(name='q')
    self.target_q = ?  # Q(name='target_q')
```

My current way is to edit the param dict similar to your approach `params['A/~/target_q'] = params['A/~/q']`, but I found editing it outside the transform is error-prone. You are right that creating networks and transforming separately avoids such problems, but I wonder if there's any better solution for the usecase mentioned above?

**Comment by tomhennigan** [comment]
Personally I would advise you to consider alternative approaches. I think doing this inside transform will overall be more error prone than doing it outside.

You might find this example of DQN useful from rlax (which uses Haiku), as you can see their approach is having a single network definition (`self._network`) and two copies of the parameters (`online_params`, `target_params`):

https://github.com/deepmind/rlax/blob/master/examples/simple_dqn.py

--

If you do decide that doing this inside transform is overall the right approach for you, then there are two things to be aware of:

1. **Lazy creation** - Unlike PyTorch, in Haiku it is typical to create parameters when a module is used rather than in `__init__`. As such you need to call the module you want to clone before you clone it.
2. **Name based reuse** - In Haiku parameter reuse is based on module naming. To achieve a "copy of the initial parameter values" between a pair of equivalent modules it is not sufficient to deepcopy it (since you would just deepcopy the module name). Instead you need to intercept Haiku's state management (e.g. get_parameter) and point it somewhere else. The utility for this (during init) is custom_creator.

I think this Colab shows how you might tie the initial value of two haiku modules together:

https://colab.research.google.com/gist/tomhennigan/b3b5a7fcde988e5a95015fe10cbf3a4d/example-of-tying-initial-parameter-values-between-modules.ipynb

**Comment by jjyyxx** [comment]
Thanks for your detailed explanation and helpful suggestion!

I rethought the way to create and organize multiple networks and decided to transform them separately as you suggested before. This might need a bit more boilerplate but avoids further difficulties of calling different networks. I guess the current solution will work smoothly, at least before some form of parameter sharing is needed.

Nevertheless, thanks for your excellent answer gist. I was thinking of using `custom_creator`, but my lack of deep understanding of `haiku` prevents me from implementing it.
