### ISSUE TITLE
Is this a correct way to save/load params?

### ISSUE THREAD

**Issue by bigyankarki** [deepmind/dm-haiku#526]
Hi simply saved the params from the trained model using jax.numpy.savez, and used np.load to load the model params. However, I get an error 
```
...
[-0.03124027],
[-0.07023009],
[ 0.03014982]], dtype=float32)}}' with dtype object is not a valid JAX array type. Only arrays of numeric types are supported by JAX.
```

I am saving params, and state as follows:
```
# save model
def save_model(path, params, st):
  jnp.savez(path, params=params, st=st)
  print("Parameters saved to ", path)
```

I am loading params, and state as follows:
```
# load model
def load_model_params(path):

  with np.load(path, allow_pickle=True) as data:
    params = data["params"]
    st = data["st"]

  return params, st
```

I assume its cause we are np.savez saves params, and st as objects, and similarly returns as objects. Is there a workaround it? I have looked through [this issue](https://github.com/deepmind/dm-haiku/issues/18). However, I don't understand if I need to implement the function as indicated in the issue discussion. Does using pickle solve this problem? Also, I am trying to initialize the params, and st from previous training iteration as follows:
```
 # init params and st from trained model if iteration > 0
    if self_play_iter > 0:
        train_logger.info('Loading trained model parameters from iteration: ' + str(self_play_iter - 1))
        path = os.path.join(trained_model_params_path, 'mod_{}.npz'.format(self_play_iter - 1))
        params, st = utils.load_model_params(path)
```

I believe as long as model is getting updated params, and st, it should be fine?

**Comment by tomhennigan** [comment]
Hi @bigyankarki , as Trevor mentioned in the issue you referenced, np.save is used to save arrays, but here you are trying to save a **tree** of arrays.

I would suggest that it would be simplest to use `pickle` to save and load your parameters:

**Comment by bigyankarki** [comment]
Ah gotcha, thank you. I was wondering why jax.device_get(params) was used in the code you referenced to? Can't we just save params directly? I see in the documentation that If params is a pytree, then the individual buffers are copied in parallel when passing through jax.device_get. Is it only for performance reasons?

**Comment by tomhennigan** [comment]
The `device_get` is mostly for performance (as you note this allows us to copy to host memory in parallel). I think you can avoid it, but personally I think it is better since it makes the data movement more explicit (e.g. `jax.device_get`: GPU -> host memory, `pickle.dump`: host memory -> disk).

The `device_put` is also for performance, this copies the NumPy arrays we load from the pickle file into GPU/TPU memory. I think this is more important, because it is quite easy to accidentally forget to do this and end up constantly copying numpy arrays to GPU memory when calling JAX functions. Again this just makes the data movement explicit (`pickle.load`: disk -> host memory, `jax.device_put`: host memory -> GPU memory).

**Comment by bigyankarki** [comment]
Thank you so much for the explanation. I was essentially able to save and load parameters. I am closing the issue.
