### ISSUE TITLE
w_init in haiku.MultiHeadAttention.__init__ is not optional

### ISSUE THREAD

**Issue by Xin-yang-Liu** [deepmind/dm-haiku#535]
In the current haiku document, the w_init is optional. However, when I try this, I got the error

> ```
> Exception has occurred: ValueError
> Please provide a weight initializer: `w_init`.
> ```

* Haiku version 0.0.8.dev
* jax 0.3.17
* jaxlib 0.3.15+cuda11+cudnn8.2

**Comment by nlsfnr** [comment]
This is because of this line [here](https://github.com/deepmind/dm-haiku/blob/main/haiku/_src/attention.py#L94) which does not allow `w_init` to be `None`, even though tat is its default value. This is because the `w_init` argument will eventually replace `w_init_scale`, however, for backwards compatibility, it has to have a default value for now. This can be quite confusing, so I added a brief explanation in the error message and additional documentation in this PR:  #541.

**Comment by tomhennigan** [comment]
Fixed via #541.
