### ISSUE TITLE
JAX version in Colab

### ISSUE THREAD

**Issue by joaogui1** [deepmind/dm-haiku#55]
Right now colab uses jax 0.1.69 and so it fails to import haiku.
I believe it would be better to add both jax and jaxlib as normal requirements, so when someone installs they get the correct versions of the dependencies.

**Comment by tomhennigan** [comment]
Thanks for the report, we've avoided pinning `jaxlib` since afaik users should pick a specific distribution of this depending on their local setup (c.f. https://github.com/google/jax#installation).

I'm open to pinning a minimum version of `jax`, but  Currently at HEAD [Haiku also relies on unreleased JAX](https://github.com/deepmind/dm-haiku/blob/master/requirements-jax.txt). We need to track JAX commits relatively closely because we use some more niche features in JAX (e.g. we have a tracer for `to_dot` and a custom primitive for `named_call`) and both JAX and Haiku are synced to [Alphabet's monorepo](https://cacm.acm.org/magazines/2016/7/204032-why-google-stores-billions-of-lines-of-code-in-a-single-repository/fulltext) where libraries need to depend on each-other and build at HEAD.

I'm planning to do a new release this week (since we just flipped the default value of `apply_rng` in `transform`) and will chat with the JAX team to get their advice on how to make this dependency more explicit.

**Comment by matpalm** [comment]
i see this is a work in progress but, just for your info, jax in colab has bumped to `0.1.72` and with `dm-haiku-0.0.1` the minimal example on readthedocs currently throws a ValueError ...

`ValueError: Apply must be called with an RNG as the second argument, the required signature is: apply(params, rng, *a, **k)`

repro eg https://colab.research.google.com/drive/1ilWQduIWKfe1HxafUH6TZdGtzOkWbiav?usp=sharing

**Comment by cgarciae** [comment]
@matpalm I think this error has nothing to do with Jax, recently `transform` had a default argument changed making `apply` request and `rng` argument. To fix it just change the last line to this:

```python
logits = forward.apply(params, rng, x)
```

**Comment by matpalm** [comment]
oh yes! i must admit i didn't properly read that error message 🤦 
i'll put a PR in and reference your solution, thanks!

**Comment by NightMachinary** [comment]
This issue should be closed, yes?
