### ISSUE TITLE
Any plans for a U-Net implementation (or otherwise commonly used network for image segmentation)?

### ISSUE THREAD

**Issue by asmith26** [deepmind/dm-haiku#97]
I've been using a lot the [Full Networks](https://dm-haiku.readthedocs.io/en/latest/api.html#module-haiku.nets) implementations, and have found them very handy (many thanks :) ).

Just wondering if there were any plans for creating a commonly used Full Network for image segmentation tasks (perhaps a U-Net based one)? Otherwise (time permitting and if useful) I'd be happy to give it a go (are there any guidelines for doing so etc).

**Comment by tomhennigan** [comment]
Hi @asmith26 , we're actually really conservative adding new nets to Haiku. In my opinion it is quite hard to ship a net that is configurable enough for everyones needs without making the code overly complicated. Also once things are in Haiku we try and ensure that they are backwards compatible ~for ever, meaning that it is quite hard to change the implementation (and we don't want to end up with "FooNet1", "FooNet2", ...). The existing nets are "grandfathered" in (so to speak) since we included them in Sonnet 1 and 2, but I think we are unlikely to add more to the repo and would instead encourage additional libraries (as part of [our "ecosystem" approach](https://deepmind.com/blog/article/using-jax-to-accelerate-our-research)).

It would be really useful for the community if you published a u-net implementation but I would suggest publishing this in a standalone library, perhaps as part of a collection of image segmentation models? I could imagine a "Haiku Vision" repo being very useful.

One piece of advice would be that often it is not too hard to implement the actual network (we at least aim to make this easy in Haiku!!) but it is hard to create an experiment that reliably reproduces some particular result. So if you do publish a u-net in Haiku it would be very useful to publish a training script and details of any experiments you've reproduced.

**Comment by asmith26** [comment]
Thanks for the explanation @tomhennigan, this makes sense.

> It would be really useful for the community if you published a u-net implementation but I would suggest publishing this in a standalone library, perhaps as part of a collection of image segmentation models? I could imagine a "Haiku Vision" repo being very useful.

Will update here on any progress I make.

> One piece of advice would be that often it is not too hard to implement the actual network (we at least aim to make this easy in Haiku!!) but it is hard to create an experiment that reliably reproduces some particular result. So if you do publish a u-net in Haiku it would be very useful to publish a training script and details of any experiments you've reproduced.

Thanks for the tip, and again for all your help!
